Add the configurable option to show the distance of a route in miles …
teemoo7/MMM-TomTomCalculateRouteTraffic pull request #9
Opened 2024-12-05 17:48 UTC by ant-garz

…instead of kilometers (default false). Update readme to show option in config. Add spanish translation file

2024-12-19 12:28 UTC, dapperbulldawg commented
Glad to see this is being added - KM is not widely recognized here.

2024-12-25 19:10 UTC, ant-garz commented
Sorry to tack on more code changes for review under this PR. I have added the display of what time of day the user is estimated to arrive at their location. Please see screenshot for reference. Thank you. 
![example](https://github.com/user-attachments/assets/ce1a4616-1e4e-4e26-adb9-80650e01e3a4)

2025-01-06 17:36 UTC, teemoo7 requested changes
Hey, many thanks for your ideas. I think there are nice proposals but some work to be done so that they can be integrated to the module.

First of all, please split them in 3 distinct PRs, as they are 3 distinct features (one for spanish translation, one for miles alternative to kms, one for estimated arrival time option).

Then, please avoid comments and doc that are useless, the code must be self-explanatory and explicit at first read. If not, then change the variable / method names accordingly.

Last but not least, please consider adding features as options, i.e. the default behavior must remain as it was, and your features can be enabled by config.

Many thanks for your contribution, just let me know if you want to work on it or if I do it when I have time. Cheers

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +			numbersSpan.className = "bright " + this.getAdjustedFontClass("medium");
Please don't change the styling. If the default style does not match your preferences, you can write your own CSS to override it.

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +				delayDiv.className = "delay " + this.getAdjustedFontClass("small");
Same

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +			nameSpan.innerHTML = calculatedRoute.route.name + " (" + calculatedRoute.calculated.lengthMi + " mi)";
Why do you replace Kilometers by Miles? I mean, that's not the default behavior. It's fine to add the option of using Miles instead of KMs (that's a good idea!) but please keep it optional, the default being metrics system.. I don't understand why you define it in the conf and don't use the `showMiles` property then..

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +			let etaSpan = document.createElement("span");
Please find a better naming than `eta`. Why not something more explicit like `estimatedArrivalTime`?

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +	 */
Please don't add such kind of "doc", it's absolutely useless, the code must be self-explaining.

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +		const conversionFactor = 0.0006213712; // Conversion factor from meters to miles
I think you can remove the comment, it's clear what this variable is

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +		const miles = meters * conversionFactor; // Convert meters to miles
Please remove the comment, the code is explicit

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +	 */
Please remove "doc" here

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +		// Get current time
Please don't comment code that is explicit 😄

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +	calculateEstimatedTimeOfArrival: function(min){
I'd recommend to use `minutes` instead of `min`, as it can be confusing with `minimum`

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +		const displayMinutes = minutes < 10 ? '0' + minutes : minutes; // Ensure 2 digits for minutes
All this time formatting must be an option. I don't use `PM` or `AM` here, and you don't use 24h time either, so we have to keep both ways. Moreover, I think MagicMirror defines some properties to format time, so I think we should rely on the default config provided by MM to know whether the use wants 24h-hour or 12-hour time format.

2025-01-06 17:36 UTC, teemoo7 commented on MMM-TomTomCalculateRouteTraffic.js
> +		const ETA = this.calculateEstimatedTimeOfArrival(timeInMinutes);
Please avoid `ETA` in capitals as a variable name. Make it explicit, that's so easier to read (and no comment is required).

2025-01-06 17:36 UTC, teemoo7 commented on README.md
> +      showMiles: false, // default to show distance in metric units
👍

2025-01-06 17:36 UTC, teemoo7 commented on README.md
> +| `showMiles `      | `false`  | Show distance in miles instead of kilometers             | `false`                       |
Please fix alignment in table (missing space)

2025-01-06 17:36 UTC, teemoo7 commented on translations/es.json
> +	"including minutes delay": "incl. {delayInMinutes} min de retraso"
👍

2025-01-09 03:09 UTC, ant-garz commented
Hi @teemoo7  ! Thanks for the feedback. I will make this adjustments in the coming days as time allows and will bump this thread once it is ready for review again

2025-01-09 03:22 UTC, ant-garz commented
To keep it clean I'm going to close this pull request and start over with a new clean one to only focus on the estimated time of arrival per your feedback above. Thanks again !

2025-01-09 03:22 UTC, closed without merging